name: Release

on:
  workflow_dispatch:
    inputs:
      draft-release:
        type: boolean
        default: false
        description: Whether to publish the release as a draft.

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

concurrency:
  group: release

jobs:
  next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@3c2d88ce0390012bac0b8383059a0b67d2594dc1

  build:
    needs: [next-version]
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      version-number: ${{ needs.next-version.outputs.new-release-version }}

  release:
    needs: [next-version, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: bundle-**
          path: tmp

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm i

      - uses: glzr-io/actions/semantic-release@main
        with:
          gh-publish: true
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          gh-draft-release: ${{ inputs.draft-release }}
          gh-assets: |
            [
              {
                "path": "tmp/bundle-x86_64-pc-windows-msvc/tauri.msi",
                "name": "zebar-${nextRelease.gitTag}-opt1-x64.msi",
                "label": "${nextRelease.gitTag} Installer (Windows x64)"
              },
              {
                "path": "tmp/bundle-aarch64-pc-windows-msvc/tauri.msi",
                "name": "zebar-${nextRelease.gitTag}-opt2-arm64.msi",
                "label": "${nextRelease.gitTag} Installer (Windows arm64)"
              },
              {
                "path": "tmp/bundle-universal-apple-darwin/tauri.dmg",
                "name": "zebar-${nextRelease.gitTag}-opt3.dmg",
                "label": "${nextRelease.gitTag} Installer (MacOS universal)"
              },
              {
                "path": "tmp/bundle-x86_64-unknown-linux-gnu/tauri.deb",
                "name": "zebar-${nextRelease.gitTag}-opt4-x64.deb",
                "label": "${nextRelease.gitTag} Installer (Linux .deb)"
              },
              {
                "path": "tmp/bundle-x86_64-unknown-linux-gnu/tauri.AppImage",
                "name": "zebar-${nextRelease.gitTag}-opt5-x64.AppImage",
                "label": "${nextRelease.gitTag} Installer (Linux AppImage)"
              }
            ]
          npm-publish: true
          npm-token: ${{ secrets.NPM_TOKEN }}
          npm-package-root: packages/client-api
          npm-package-manager: pnpm
